name: xgems

{% set python_version = os.environ.get("PY_VER", "3.7") %}

dependencies:
  - gxx_linux-64=7.3.0  # [linux]
  - cmake>=3.13
  - make
  - git
  - ccache  # [unix]
  - pybind11
  - eigen
  - pytest
  - gems3k=4.3.1
  - python={{ python_version }}

environment:

  PYTHONPATH:
    - {{ root }}/artifacts/python/lib/python{{ python_version }}/site-packages   # [unix]
    - {{ root }}/build/lib/python{{ python_version }}/site-packages              # [unix]
    - {{ root }}/build/lib64/python{{ python_version }}/site-packages            # [unix]
    - {{ root }}\artifacts\python\Lib\site-packages                              # [win]
    - {{ root }}\build\lib\python{{ python_version }}\site-packages              # [win]

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]
