name: xgems


channels:
  - conda-forge

dependencies:
  - setuptools=59.7.0
  - gxx_linux-64  # [linux]
  - cmake>=3.13
  - make
  - git
  - ccache  # [unix]
  - pybind11
  - eigen
  - pytest
  - thermofun>=0.4.3
  - gems3k>=4.3.5
  - python

environment:

  PYTHONPATH:
    - {{ root }}/artifacts/python/lib/python{{ python_version }}/site-packages   # [unix]
    - {{ root }}/build/lib/python{{ python_version }}/site-packages              # [unix]
    - {{ root }}/build/lib64/python{{ python_version }}/site-packages            # [unix]
    - {{ root }}\artifacts\python\Lib\site-packages                              # [win]
    - {{ root }}\build\lib\python{{ python_version }}\site-packages              # [win]

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]
