from __future__ import annotations

from typing import Dict, List, Optional, overload

import numpy as np

# ---------------------------------------------------------------------------
# Free functions
# ---------------------------------------------------------------------------

def update_loggers(use_cout: bool, logfile_name: str, log_level: int) -> None: ...
def parse_chemical_formula(formula: str) -> Dict[str, float]: ...

# ---------------------------------------------------------------------------
# ChemicalEngineOptions
# ---------------------------------------------------------------------------

class ChemicalEngineOptions:
    warmstart: bool
    print_zero_amounts: bool
    def __init__(self) -> None: ...

# ---------------------------------------------------------------------------
# ChemicalEngine
# ---------------------------------------------------------------------------

class ChemicalEngine:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, filename: str) -> None: ...
    def initialize(self, filename: str) -> None: ...
    def initializeFromJsonStrings(
        self, dch_json: str, ipm_json: str, dbr_json: str
    ) -> None: ...
    def readDbrFromFile(self, filename: str) -> None: ...
    def readDbrFromJsonString(self, dbr_json: str) -> None: ...
    def writeDbrToFile(self, filename: str) -> None: ...
    def writeDbrToJsonString(self) -> str: ...

    # System dimensions
    def numElements(self) -> int: ...
    def numSpecies(self) -> int: ...
    def numPhases(self) -> int: ...
    @overload
    def numSpeciesInPhase(self, iphase: int) -> int: ...
    @overload
    def numSpeciesInPhase(self, phase: str) -> int: ...
    def numSpeciesInPhase_i(self, iphase: int) -> int: ...

    # Names
    def elementName(self, index: int) -> str: ...
    def elementName_i(self, index: int) -> str: ...
    def speciesName(self, index: int) -> str: ...
    def speciesName_i(self, index: int) -> str: ...
    def phaseName(self, index: int) -> str: ...
    def phaseName_i(self, index: int) -> str: ...

    # Species charge
    @overload
    def speciesCharge(self, index: int) -> float: ...
    @overload
    def speciesCharge(self, species: str, phase: Optional[str] = ...) -> float: ...
    def speciesCharge_i(self, index: int) -> float: ...

    # Index lookups
    def indexElement(self, name: str) -> int: ...
    def indexSpecies(self, name: str, phase: Optional[str] = ...) -> int: ...
    def indexSpeciesAll(self, name: str) -> List[int]: ...
    def indexSpeciesMap(self, name: str) -> Dict[str, int]: ...
    def indexPhase(self, name: str) -> int: ...
    def indexPhaseAll(self, name: str) -> List[int]: ...
    def indexPhaseWithSpecies(self, species_index: int) -> int: ...
    @overload
    def indexFirstSpeciesInPhase(self, iphase: int) -> int: ...
    @overload
    def indexFirstSpeciesInPhase(self, phase: str) -> int: ...
    def indexFirstSpeciesInPhase_i(self, iphase: int) -> int: ...

    # Matrices / vectors
    def elementMolarMasses(self) -> np.ndarray: ...
    def speciesMolarMasses(self) -> np.ndarray: ...
    def formulaMatrix(self) -> np.ndarray: ...

    # Options
    @property
    def options(self) -> ChemicalEngineOptions: ...
    @options.setter
    def options(self, value: ChemicalEngineOptions) -> None: ...
    def setWarmStart(self) -> None: ...
    def setColdStart(self) -> None: ...

    # Species limits / amounts
    @overload
    def setSpeciesUpperLimit(
        self, name: str, limit: float, phase: Optional[str] = ...
    ) -> None: ...
    @overload
    def setSpeciesUpperLimit(self, index: int, limit: float) -> None: ...
    def setSpeciesUpperLimit_i(self, index: int, limit: float) -> None: ...
    @overload
    def setSpeciesLowerLimit(
        self, name: str, limit: float, phase: Optional[str] = ...
    ) -> None: ...
    @overload
    def setSpeciesLowerLimit(self, index: int, limit: float) -> None: ...
    def setSpeciesLowerLimit_i(self, index: int, limit: float) -> None: ...
    @overload
    def setSpeciesAmount(
        self, name: str, amount: float, phase: Optional[str] = ...
    ) -> None: ...
    @overload
    def setSpeciesAmount(self, ispecies: int, amount: float) -> None: ...
    def setSpeciesAmount_i(self, ispecies: int, amount: float) -> None: ...

    # Standard Gibbs energy
    @overload
    def setStandardMolarGibbsEnergy(
        self, name: str, value: float, phase: Optional[str] = ...
    ) -> None: ...
    @overload
    def setStandardMolarGibbsEnergy(self, ispecies: int, value: float) -> None: ...
    def setStandardMolarGibbsEnergy_i(self, ispecies: int, value: float) -> None: ...

    # State setters
    def setPT(self, temperature: float, pressure: float) -> bool: ...
    def setB(self, composition: List[float]) -> None: ...

    # Equilibration
    @overload
    def reequilibrate(self) -> int: ...
    @overload
    def reequilibrate(self, warmstart: bool) -> int: ...
    def equilibrate(self, T: float, P: float, b: np.ndarray) -> int: ...

    # Convergence / diagnostics
    def converged(self) -> bool: ...
    def numIterations(self) -> int: ...
    def elapsedTime(self) -> float: ...

    # Scalar state
    def temperature(self) -> float: ...
    def pressure(self) -> float: ...
    def ionicStrength(self) -> float: ...
    def pH(self) -> float: ...
    def pe(self) -> float: ...
    def Eh(self) -> float: ...
    def systemMass(self) -> float: ...
    def systemVolume(self) -> float: ...
    def systemGibbsEnergy(self) -> float: ...
    def systemEnthalpy(self) -> float: ...
    def systemEntropy(self) -> float: ...
    def systemHeatCapacityConstP(self) -> float: ...
    def aqueousPhaseName(self) -> str: ...
    def gasPhaseName(self) -> str: ...

    # Element amounts
    def elementAmounts(self) -> np.ndarray: ...
    @overload
    def elementAmountsInPhase(self, iphase: int) -> np.ndarray: ...
    @overload
    def elementAmountsInPhase(self, phase: str) -> np.ndarray: ...
    def elementAmountsInPhase_i(self, iphase: int) -> np.ndarray: ...
    def elementAmountsInSpecies(self, species_index: int) -> np.ndarray: ...

    # Species amounts / bulk vectors
    @overload
    def speciesAmount(self, ispecies: int) -> float: ...
    @overload
    def speciesAmount(self, name: str, phase: Optional[str] = ...) -> float: ...
    def speciesAmount_i(self, ispecies: int) -> float: ...
    def setSpeciesAmounts(self, amounts: List[float]) -> None: ...
    def speciesAmounts(self) -> np.ndarray: ...
    def setSpeciesUpperLimits(self, limits: List[float]) -> None: ...
    def setSpeciesLowerLimits(self, limits: List[float]) -> None: ...
    def speciesUpperLimits(self) -> np.ndarray: ...
    def speciesLowerLimits(self) -> np.ndarray: ...

    # Species thermodynamic properties
    def moleFractions(self) -> np.ndarray: ...
    def speciesMolalities(self) -> np.ndarray: ...
    def lnActivityCoefficients(self) -> np.ndarray: ...
    def lnActivities(self) -> np.ndarray: ...
    def lnConcentrations(self) -> np.ndarray: ...
    def chemicalPotentials(self) -> np.ndarray: ...
    @overload
    def standardMolarGibbsEnergy(self, ispecies: int) -> float: ...
    @overload
    def standardMolarGibbsEnergy(
        self, species: str, phase: Optional[str] = ...
    ) -> float: ...
    def standardMolarGibbsEnergy_i(self, ispecies: int) -> float: ...
    @overload
    def standardMolarEnthalpy(self, ispecies: int) -> float: ...
    @overload
    def standardMolarEnthalpy(
        self, species: str, phase: Optional[str] = ...
    ) -> float: ...
    def standardMolarEnthalpy_i(self, ispecies: int) -> float: ...
    @overload
    def standardMolarVolume(self, ispecies: int) -> float: ...
    @overload
    def standardMolarVolume(
        self, species: str, phase: Optional[str] = ...
    ) -> float: ...
    def standardMolarVolume_i(self, ispecies: int) -> float: ...
    @overload
    def standardMolarEntropy(self, ispecies: int) -> float: ...
    @overload
    def standardMolarEntropy(
        self, species: str, phase: Optional[str] = ...
    ) -> float: ...
    def standardMolarEntropy_i(self, ispecies: int) -> float: ...
    @overload
    def standardMolarHeatCapacityConstP(self, ispecies: int) -> float: ...
    @overload
    def standardMolarHeatCapacityConstP(
        self, species: str, phase: Optional[str] = ...
    ) -> float: ...
    def standardMolarHeatCapacityConstP_i(self, ispecies: int) -> float: ...

    # Phase molar properties
    @overload
    def phaseMolarGibbsEnergy(self, iphase: int) -> float: ...
    @overload
    def phaseMolarGibbsEnergy(self, phase: str) -> float: ...
    def phaseMolarGibbsEnergy_i(self, iphase: int) -> float: ...
    @overload
    def phaseMolarEnthalpy(self, iphase: int) -> float: ...
    @overload
    def phaseMolarEnthalpy(self, phase: str) -> float: ...
    def phaseMolarEnthalpy_i(self, iphase: int) -> float: ...
    @overload
    def phaseMolarVolume(self, iphase: int) -> float: ...
    @overload
    def phaseMolarVolume(self, phase: str) -> float: ...
    def phaseMolarVolume_i(self, iphase: int) -> float: ...
    @overload
    def phaseMolarEntropy(self, iphase: int) -> float: ...
    @overload
    def phaseMolarEntropy(self, phase: str) -> float: ...
    def phaseMolarEntropy_i(self, iphase: int) -> float: ...
    @overload
    def phaseMolarHeatCapacityConstP(self, iphase: int) -> float: ...
    @overload
    def phaseMolarHeatCapacityConstP(self, phase: str) -> float: ...
    def phaseMolarHeatCapacityConstP_i(self, iphase: int) -> float: ...

    # Phase specific properties
    @overload
    def phaseSpecificGibbsEnergy(self, iphase: int) -> float: ...
    @overload
    def phaseSpecificGibbsEnergy(self, phase: str) -> float: ...
    def phaseSpecificGibbsEnergy_i(self, index: int) -> float: ...
    @overload
    def phaseSpecificEnthalpy(self, iphase: int) -> float: ...
    @overload
    def phaseSpecificEnthalpy(self, phase: str) -> float: ...
    def phaseSpecificEnthalpy_i(self, iphase: int) -> float: ...
    @overload
    def phaseSpecificVolume(self, iphase: int) -> float: ...
    @overload
    def phaseSpecificVolume(self, phase: str) -> float: ...
    def phaseSpecificVolume_i(self, iphase: int) -> float: ...
    @overload
    def phaseSpecificEntropy(self, iphase: int) -> float: ...
    @overload
    def phaseSpecificEntropy(self, phase: str) -> float: ...
    def phaseSpecificEntropy_i(self, iphase: int) -> float: ...
    @overload
    def phaseSpecificHeatCapacityConstP(self, iphase: int) -> float: ...
    @overload
    def phaseSpecificHeatCapacityConstP(self, phase: str) -> float: ...
    def phaseSpecificHeatCapacityConstP_i(self, iphase: int) -> float: ...

    # Phase bulk properties (vectors)
    def phaseDensities(self) -> np.ndarray: ...
    @overload
    def phaseDensity(self, iphase: int) -> float: ...
    @overload
    def phaseDensity(self, phase: str) -> float: ...
    def phaseDensity_i(self, iphase: int) -> float: ...
    def phaseMasses(self) -> np.ndarray: ...
    @overload
    def phaseMass(self, iphase: int) -> float: ...
    @overload
    def phaseMass(self, phase: str) -> float: ...
    def phaseMass_i(self, iphase: int) -> float: ...
    def phaseAmounts(self) -> np.ndarray: ...
    @overload
    def phaseAmount(self, iphase: int) -> float: ...
    @overload
    def phaseAmount(self, phase: str) -> float: ...
    def phaseAmount_i(self, iphase: int) -> float: ...
    def phaseVolumes(self) -> np.ndarray: ...
    @overload
    def phaseVolume(self, iphase: int) -> float: ...
    @overload
    def phaseVolume(self, phase: str) -> float: ...
    def phaseVolume_i(self, iphase: int) -> float: ...
    def phaseEnthalpies(self) -> np.ndarray: ...
    @overload
    def phaseEnthalpy(self, iphase: int) -> float: ...
    @overload
    def phaseEnthalpy(self, phase: str) -> float: ...
    def phaseEnthalpy_i(self, iphase: int) -> float: ...
    def phaseEntropies(self) -> np.ndarray: ...
    @overload
    def phaseEntropy(self, iphase: int) -> float: ...
    @overload
    def phaseEntropy(self, phase: str) -> float: ...
    def phaseEntropy_i(self, iphase: int) -> float: ...
    def phaseHeatCapacitiesConstP(self) -> np.ndarray: ...
    @overload
    def phaseHeatCapacityConstP(self, iphase: int) -> float: ...
    @overload
    def phaseHeatCapacityConstP(self, phase: str) -> float: ...
    def phaseHeatCapacityConstP_i(self, iphase: int) -> float: ...
    def phaseSatIndices(self) -> np.ndarray: ...
    @overload
    def phaseSatIndex(self, iphase: int) -> float: ...
    @overload
    def phaseSatIndex(self, phase: str) -> float: ...
    def phaseSatIndex_i(self, iphase: int) -> float: ...

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# ChemicalEngineDicts  (C++ ChemicalEngineMaps)
# ---------------------------------------------------------------------------

class ChemicalEngineDicts:
    T: float
    P: float

    def __init__(
        self,
        input_file: str,
        reset_calc: bool = ...,
        cold_start: bool = ...,
    ) -> None: ...

    # Read-only system info
    @property
    def element_names(self) -> List[str]: ...
    @property
    def species_names(self) -> List[str]: ...
    @property
    def phase_names(self) -> List[str]: ...
    @property
    def aq_phase_symbol(self) -> str: ...
    @property
    def gas_phase_symbol(self) -> str: ...
    @property
    def element_molar_masses(self) -> Dict[str, float]: ...
    @property
    def species_in_phase(self) -> Dict[str, List[str]]: ...
    @property
    def species_charges(self) -> Dict[str, float]: ...
    @property
    def species_molar_mass(self) -> Dict[str, float]: ...
    @property
    def species_molar_volumes(self) -> Dict[str, float]: ...
    @property
    def nelements(self) -> int: ...
    @property
    def nphases(self) -> int: ...
    @property
    def nspecies(self) -> int: ...

    # Equilibration
    @overload
    def equilibrate(self) -> str: ...
    @overload
    def equilibrate(
        self,
        T: float,
        P: float,
        b_dict: Dict[str, float],
        min_amount: float = ...,
    ) -> str: ...
    @overload
    def reequilibrate(self) -> str: ...
    @overload
    def reequilibrate(self, warmstart: bool) -> str: ...

    # State setters
    def setPT(self, P: float, T: float) -> bool: ...
    def setB(self, b_dict: Dict[str, float], min_amount: float = ...) -> None: ...
    def set_bulk_composition(
        self, b_input: Dict[str, float], min_amount: float = ...
    ) -> None: ...
    def reset_aq_composition(self, min_amount: float = ...) -> None: ...
    def cold_start(self) -> None: ...
    def warm_start(self) -> None: ...
    def clear(self, min_amount: float = ...) -> None: ...
    def set_species_G0(
        self, name: str, value: float, phase: Optional[str] = ...
    ) -> None: ...

    # DBR I/O
    def readDbrFromFile(self, filename: str) -> None: ...
    def readDbrFromJsonString(self, dbr_json: str) -> None: ...
    def writeDbrToFile(self, filename: str) -> None: ...
    def writeDbrToJsonString(self) -> str: ...

    # Scalar state after equilibration
    @property
    def temperature(self) -> float: ...
    @property
    def pressure(self) -> float: ...
    @property
    def pH(self) -> float: ...
    @property
    def pE(self) -> float: ...
    @property
    def ionic_strength(self) -> float: ...
    @property
    def Eh(self) -> float: ...
    @property
    def converged(self) -> bool: ...
    @property
    def num_iterations(self) -> int: ...
    @property
    def elapsed_time(self) -> float: ...
    @property
    def system_volume(self) -> float: ...
    @property
    def system_mass(self) -> float: ...
    @property
    def system_gibbs_energy(self) -> float: ...
    @property
    def system_enthalpy(self) -> float: ...
    @property
    def system_entropy(self) -> float: ...
    @property
    def system_heat_capacity_const_p(self) -> float: ...
    @property
    def aq_volume_frac(self) -> float: ...

    # Composition
    @property
    def bulk_composition(self) -> Dict[str, float]: ...
    @property
    def aq_elements_molarity(self) -> Dict[str, float]: ...
    @property
    def aq_elements_molality(self) -> Dict[str, float]: ...
    @property
    def aq_species_molarity(self) -> Dict[str, float]: ...
    @property
    def aq_species_molality(self) -> Dict[str, float]: ...
    @property
    def aq_elements_moles(self) -> Dict[str, float]: ...
    def solids_elements_moles(
        self,
        min_amount_phase: float = ...,
        min_amount_element: float = ...,
    ) -> Dict[str, float]: ...
    @property
    def phases_elements_moles(self) -> Dict[str, Dict[str, float]]: ...
    @overload
    def phase_species_moles(self) -> Dict[str, Dict[str, float]]: ...
    @overload
    def phase_species_moles(self, name: str) -> Dict[str, float]: ...
    @property
    def phases_moles(self) -> Dict[str, float]: ...
    @property
    def species_moles(self) -> Dict[str, float]: ...

    # Phase properties
    @property
    def phases_molar_volume(self) -> Dict[str, float]: ...
    @property
    def phase_sat_indices(self) -> Dict[str, float]: ...
    @property
    def phases_density(self) -> Dict[str, float]: ...
    @property
    def phases_enthalpy(self) -> Dict[str, float]: ...
    @property
    def phases_entropy(self) -> Dict[str, float]: ...
    @property
    def phases_molar_gibbs_energy(self) -> Dict[str, float]: ...
    @property
    def phases_heat_capacity_const_p(self) -> Dict[str, float]: ...
    @property
    def phases_volume(self) -> Dict[str, float]: ...
    @property
    def phases_mass(self) -> Dict[str, float]: ...
    @property
    def phases_volume_frac(self) -> Dict[str, float]: ...
    @property
    def solids_mass_frac(self) -> Dict[str, float]: ...
    @property
    def solids_volume_frac(self) -> Dict[str, float]: ...

    # Species thermodynamic properties
    @property
    def species_ln_activities(self) -> Dict[str, float]: ...
    @property
    def species_ln_activity_coefficients(self) -> Dict[str, float]: ...
    @property
    def species_mole_fractions(self) -> Dict[str, float]: ...
    @property
    def species_ln_concentrations(self) -> Dict[str, float]: ...
    @property
    def species_chemical_potentials(self) -> Dict[str, float]: ...
    @property
    def species_gibbs_energies(self) -> Dict[str, float]: ...
    @property
    def species_enthalpies(self) -> Dict[str, float]: ...
    @property
    def species_entropies(self) -> Dict[str, float]: ...
    @property
    def species_heat_capacities_const_p(self) -> Dict[str, float]: ...
    @property
    def species_upper_bounds(self) -> Dict[str, float]: ...
    @property
    def species_lower_bounds(self) -> Dict[str, float]: ...
    @property
    def phase_species_ln_activities(self) -> Dict[str, Dict[str, float]]: ...
    @property
    def phase_species_ln_activity_coefficients(
        self,
    ) -> Dict[str, Dict[str, float]]: ...
    @property
    def phase_species_upper_bounds(self) -> Dict[str, Dict[str, float]]: ...
    @property
    def phase_species_lower_bounds(self) -> Dict[str, Dict[str, float]]: ...

    # Amount manipulation
    def add_multiple_species_amt(
        self, input_dict: Dict[str, float], units: str = ...
    ) -> None: ...
    def add_species_amt(
        self,
        species: str,
        val: float,
        units: str = ...,
        phase: Optional[str] = ...,
    ) -> None: ...
    def add_element_amt(
        self, element_name: str, val: float, units: str = ...
    ) -> None: ...
    def add_multiple_elements_amt(
        self, input_dict: Dict[str, float], units: str = ...
    ) -> None: ...
    def add_amt_from_formula(
        self, formula: Dict[str, float], val: float, units: str = ...
    ) -> None: ...
    def get_b_from_formula(
        self,
        formula: Dict[str, float],
        val: float = ...,
        units: str = ...,
        min_amount: float = ...,
    ) -> List[float]: ...

    # Bounds
    def set_multiple_species_lower_bound(
        self, input_dict: Dict[str, float], units: str = ...
    ) -> None: ...
    def set_multiple_species_upper_bound(
        self, input_dict: Dict[str, float], units: str = ...
    ) -> None: ...
    @overload
    def set_species_lower_bound(
        self,
        species: str,
        val: float,
        units: str = ...,
        phase: Optional[str] = ...,
    ) -> None: ...
    @overload
    def set_species_lower_bound(
        self, ispecies: int, val: float, units: str = ...
    ) -> None: ...
    @overload
    def set_species_upper_bound(
        self,
        species: str,
        val: float,
        units: str = ...,
        phase: Optional[str] = ...,
    ) -> None: ...
    @overload
    def set_species_upper_bound(
        self, ispecies: int, val: float, units: str = ...
    ) -> None: ...

    # Phase / species suppression
    def suppress_phase(
        self,
        phase_name: str,
        min_amount: float = ...,
        max_amount: float = ...,
    ) -> None: ...
    def suppress_multiple_phases(
        self,
        phase_name_list: List[str],
        min_amount: float = ...,
        max_amount: float = ...,
    ) -> None: ...
    def suppress_species(
        self,
        species_name: str,
        min_amount: float = ...,
        max_amount: float = ...,
        phase: Optional[str] = ...,
    ) -> None: ...
    def suppress_multiple_species(
        self,
        species_list: List[str],
        min_amount: float = ...,
        max_amount: float = ...,
    ) -> None: ...
    def activate_phase(self, phase_name: str) -> None: ...
    def activate_multiple_phases(self, phase_name_list: List[str]) -> None: ...
    def activate_species(
        self, species_name: str, phase: Optional[str] = ...
    ) -> None: ...
    def activate_multiple_species(self, species_list: List[str]) -> None: ...

    def __repr__(self) -> str: ...

    # ------------------------------------------------------------------
    # Aliases (set via gems.attr(...) in the C++ binding)
    # ------------------------------------------------------------------
    @property
    def vector_b(self) -> Dict[str, float]: ...
    @property
    def aq_el_M(self) -> Dict[str, float]: ...
    @property
    def aq_el_my(self) -> Dict[str, float]: ...
    @property
    def aq_species_composition(self) -> Dict[str, float]: ...
    @property
    def aq_sp_M(self) -> Dict[str, float]: ...
    @property
    def aq_sp_my(self) -> Dict[str, float]: ...
    @property
    def aq_composition(self) -> Dict[str, float]: ...
    @property
    def aq_elements_amounts(self) -> Dict[str, float]: ...
    def set_vector_b(
        self, b_input: Dict[str, float], min_amount: float = ...
    ) -> None: ...
    def clear_b_aq_part(self, min_amount: float = ...) -> None: ...
    def solid_elements_amounts(
        self,
        min_amount_phase: float = ...,
        min_amount_element: float = ...,
    ) -> Dict[str, float]: ...
    @property
    def phase_elements_amounts(self) -> Dict[str, Dict[str, float]]: ...
    @property
    def phase_amounts(self) -> Dict[str, float]: ...
    @property
    def species_amounts(self) -> Dict[str, float]: ...
    def phase_species_amounts(self) -> Dict[str, Dict[str, float]]: ...
    @property
    def solid_mass_frac(self) -> Dict[str, float]: ...
    @property
    def solid_volume_frac(self) -> Dict[str, float]: ...
    @property
    def phase_volumes(self) -> Dict[str, float]: ...
    @property
    def phase_masses(self) -> Dict[str, float]: ...
    @property
    def phase_volume_frac(self) -> Dict[str, float]: ...
    def vector_b_from_formula(
        self,
        formula: Dict[str, float],
        val: float = ...,
        units: str = ...,
        min_amount: float = ...,
    ) -> List[float]: ...
    def multiple_species_lower_bound(
        self, input_dict: Dict[str, float], units: str = ...
    ) -> None: ...
    def multiple_species_upper_bound(
        self, input_dict: Dict[str, float], units: str = ...
    ) -> None: ...
    @property
    def IS(self) -> float: ...
    @property
    def phase_molar_volume(self) -> Dict[str, float]: ...
    @property
    def phases_sat_index(self) -> Dict[str, float]: ...
    @property
    def phases_SI(self) -> Dict[str, float]: ...

# ---------------------------------------------------------------------------
# Material
# ---------------------------------------------------------------------------

class Material:
    name: str
    min_amount: float

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, engine: ChemicalEngine, name: str = ...) -> None: ...
    @overload
    def __init__(self, engine: ChemicalEngineDicts, name: str = ...) -> None: ...

    @overload
    def add(
        self,
        formula: str,
        value: float = ...,
        units: str = ...,
        react_ext: float = ...,
    ) -> "Material": ...
    @overload
    def add(
        self,
        formula: Dict[str, float],
        value: Optional[float] = ...,
        units: str = ...,
        react_ext: float = ...,
    ) -> "Material": ...

    def __call__(self, value: float = ..., units: str = ...) -> "Material": ...
    def __add__(self, other: "Material") -> "Material": ...
    def scale(self, factor: float) -> "Material": ...
    def scale_to_mass(self, kg: float) -> "Material": ...
    def scale_to_moles(self, mol: float) -> "Material": ...
    def set_quantity(self, value: float, units: str = ...) -> "Material": ...
    def elements(self) -> Dict[str, float]: ...
    def b(self) -> np.ndarray: ...
    def b_dict(self) -> Dict[str, float]: ...
    def mass_kg(self) -> float: ...
    def moles(self) -> float: ...
    def total(self, units: str = ...) -> float: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
